name: "Teable Community Edition"
version: "1.0.0"
slug: "teable"
description: "Teable Community Edition for Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
options:
  prisma_database_url: "postgres://teable:teable@77b2833f-timescaledb:5432/teable"
  public_origin: "http://127.0.0.1:3000"
schema:
  prisma_database_url: str
  public_origin: str
ports:
  "3000/tcp": 3000
